### ISSUE TITLE
Covered - Is it an official branch now?

### ISSUE THREAD

**Issue by oleg-nenashev** [chiphackers/covered#1]
Hi @udara28. Is it an official branch of covered now (aka "is it something confirmed by previous maintainer")? Just want to get more info about your plans regarding this tool, want to try it in my pet projects

**Comment by udara28** [comment]
Yes this is now the official branch for covered. master branch is created from stable-0_7-branch from old cvs repository.

**Comment by udara28** [comment]
Added a link in the official sourceforge project page for this repository to redirect users
https://sourceforge.net/projects/covered/
